---
- hosts: all
  become: yes
  tasks:
    - name: Wait for cloud-init / user-data to finish
      command: cloud-init status --wait
      changed_when: false
- hosts: frontend
  become: yes
  tasks:
    - name: grab variable data from backend
      debug:
        var: vip
    - name: Install Keepalived
      apt:
        name: keepalived
        state: latest

    - name: Configure Keepalived
      template:
        src: templates/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
      notify: restart keepalived

    - name: Ensure Keepalived service is enabled and started
      service:
        name: keepalived
        state: started
        enabled: yes
  handlers:
    - name: restart keepalived
      service:
        name: keepalived
        state: restarted

- hosts: backend
  become: yes
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: latest

    - name: Configure Netplan
      template:
        src: templates/60-lvs.yaml.j2
        dest: /etc/netplan/60-lvs.yaml
      notify: restart netplan

    - name: Create a test HTML file
      copy:
        content: "<html><body><h1>Hello from backend server</h1></body></html>"
        dest: /var/www/html/index.html

    - name: Ensure Apache2 service is enabled and started
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Add arp_ignore (IPv4) to sysctl.conf for All Interfaces
      sysctl:
        sysctl_file: /etc/sysctl.d/90-lvs.conf
        name: net.ipv4.conf.all.arp_ignore
        value: 1

    - name: Add arp_ignore (IPv4) to sysctl.conf for All Interfaces
      sysctl:
        sysctl_file: /etc/sysctl.d/90-lvs.conf
        name: net.ipv4.conf.all.arp_announce
        value: 2

  handlers:
    - name: restart netplan
      shell: netplan apply
